name:                servant-streamly
version:             0.1.0
github:              "blackheaven/servant-streamly"
license:             BSD3
author:              "Gautier DI FOLCO"
maintainer:          "gautier.difolco@gmail.com"
copyright:           "Gautier DI FOLCO"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Servant Stream support for streamly.
category:            Web, Servant, Streamly

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Servant Stream support for streamly. Provides 'ToSourceIO' and 'FromSourceIO' instances for all 'IsStream' instances.

dependencies:
- base >= 4.7 && < 5
- servant >= 0.16 && < 0.17
- streamly >= 0.7.2 && < 0.8
- resourcet >= 1.2.4.2 && < 1.3

library:
  source-dirs: src

executables:
  servant-streamly-example:
    main:                Main.hs
    source-dirs:         example
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytestring >= 0.10.10.0 && < 0.11
    - http-client >= 0.6.4.1 && < 0.7
    - servant
    - servant-client >= 0.16 && < 0.17
    - servant-server >= 0.16 && < 0.17
    - servant-streamly
    - streamly
    - streamly-bytestring >= 0.1.2 && < 0.2
    - wai >= 3.2.2.1 && < 3.3
    - warp >= 3.3.13 && < 3.4

tests:
  servant-streamly-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec >= 2.7.1 && < 2.8
    - servant-server
    - servant-streamly
